{
  "openapi": "3.0.1",
  "info": {
    "title": "GO1 API",
    "description": "\nGO1 API has been built to make it easy to integrate GO1 with external systems.\n\nAll endpoints are only accessible via https and are located at `api.go1.com`.\n\nGO1 supports users belonging to one or more portals. This API only supports accessing data from one portal at a time. If you need to retrieve data from multiple portals you will need to authenticate with each portal and separately request the data.\n\n# Authentication\nGO1 uses the standard OAuth 2.0 protocol to p[...]",
    "termsOfService": "https://www.go1.com/terms/user-terms",
    "version": "v2"
  },
  "servers": [
    {
      "url": "https://api.go1.com"
    }
  ],
  "tags": [
    {
      "name": "Account",
      "description": "Gets details about the portal you are requesting for. E.g. Number of users in plan, URL, active user count."
    },
    {
      "name": "Award",
      "description": "Allows creation of awards in a portal."
    },
    {
      "name": "Collections",
      "description": "Allows management of the default collection. The default collection is a subset of portal content which can be curated by Admins as desired. There is only one such collection per portal currently."
    },
    {
      "name": "Configuration"
    },
    {
      "name": "Enrollments",
      "description": "Allows operators to fetch or create enrolments. Note that you may fetch enrolments for a portal, or you can pass a userid to fetch enrolments for a particular user(s)."
    },
    {
      "name": "Learning Activity",
      "description": "Allows operators to fetch their own SCORM request payloads by `enrollment-id`."
    },
    {
      "name": "Learning Content",
      "description": "Allows the operator to retrieve content from our Explore service, which essentially contains all the content for the portal. This includes Premium, customer-created content as well as Marketplace content. Using the parameter subscribe=true filters out “Marketplace”, which is recommended."
    },
    {
      "name": "Users",
      "description": "Allows operators to retrieve or manage user accounts and associated details."
    },
    {
      "name": "User Groups",
      "description": "Allows management of User Group."
    },
    {
      "name": "Webhooks",
      "description": "Webhooks are also available from the GO1 product to enable your application to catch and receive updates regarding enrolments, content and users.\n\n\n## user_create event\n\nThe `user_create` event is triggered whenever a new user is created within a Go1 portal.\n\n<SchemaDefinition schemaRef=\"#/components/schemas/WebhookUserCreatePayload\" />\n\n## user_update event\n\nThe `user_update` event is triggered whenever an user is updated in Go1.\n\n<SchemaDefinition schemaRef[...]"
    },
    {
      "name": "Onboarding",
      "description": "Allows the creation of a new customer portal and provision some admin user accounts at the same time, as desired."
    },
    {
      "name": "Data Mapping",
      "description": "Allows operators to retrieve or manage data mapping and associated details."
    }
  ],
  "paths": {
    "/v2/account": {
      "get": {
        "tags": ["Account"],
        "summary": "Get portal details",
        "description": "Detailed information about the portal the token is connected to. Including information about features activated and the billing plan.",
        "security": [
          {
            "OAuth2": ["account.read"]
          }
        ]
      }
    },
    "/v2/award": {
      "post": {
        "tags": ["Award"],
        "summary": "Add awards to a portal",
        "security": [
          {
            "OAuth2": ["lo.write"]
          }
        ]
      }
    },
    "/v2/award/{awardId}": {
      "get": {
        "tags": ["Award"],
        "summary": "Loads an award from the portal",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/collections/{collection-id}/items/add": {
      "post": {
        "tags": ["Collections"],
        "summary": "Add items to a collection",
        "security": [
          {
            "OAuth2": ["lo.write"]
          }
        ]
      }
    },
    "/v2/collections/{collection-id}/items/remove": {
      "post": {
        "tags": ["Collections"],
        "summary": "Remove items from a collection",
        "security": [
          {
            "OAuth2": ["lo.write"]
          }
        ]
      }
    },
    "/v2/configuration": {
      "get": {
        "tags": ["Configuration"],
        "summary": "Get portal configuration",
        "description": "Gets the key value configuration pairs for a portal.",
        "security": [
          {
            "OAuth2": ["portal.read"]
          }
        ]
      },
      "put": {
        "tags": ["Configuration"],
        "summary": "Modify portal configuration",
        "description": "Creates or updates the key value configuration pairs as sent in the request body.",
        "security": [
          {
            "OAuth2": ["portal.write"]
          }
        ]
      }
    },
    "/v2/learning-activity": {
      "get": {
        "tags": ["Learning Activity"],
        "summary": "Fetch a SCORM request payload (Beta)",
        "description": "`BETA` \n\nFetch the raw SCORM request payload associated with any of your enrollments.\n\nThe payload includes everything supplied in the original SCORM request.",
        "security": [
          {
            "OAuth2": ["enrollment.read"]
          }
        ]
      }
    },
    "/v2/competency/related-roles": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Fetch related roles (Experimental)",
        "description": "Note: This endpoint is still in an experimental phase, please contact support first if you want to use it! Returns roles in the GO1 system which are similar to the one provided.",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/competency/roles": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Endpoint to search for (Experimental)",
        "description": "Note: This endpoint is still in an experimental phase, please contact support first if you want to use it! Returns roles based on role parameter for autocomplete or based on skill parameter.",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/competency/skills": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Endpoint to search for skills (Experimental)",
        "description": "Note: This endpoint is still in an experimental phase, please contact support first if you want to use it! Returns roles based on skill parameter for autocomplete or based on role parameter.",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/content/links": {
      "post": {
        "tags": ["Learning Content"],
        "summary": "Create a new link",
        "description": "Creates a new standalone `link` type learning item.",
        "security": [
          {
            "OAuth2": ["lo.write"]
          }
        ]
      }
    },
    "/v2/content/manual": {
      "post": {
        "tags": ["Learning Content"],
        "summary": "Create a new manual learning item",
        "description": "Creates a new standalone `manual` type learning item.",
        "security": [
          {
            "OAuth2": ["lo.write"]
          }
        ]
      }
    },
    "/v2/enrollments": {
      "get": {
        "tags": ["Enrollments"],
        "summary": "List enrollments",
        "description": "Gets a list of enrollments in the portal.\n\nNote: If the `user_id` parameter is not present, the authenticated user must be a portal administrator.\n",
        "security": [
          {
            "OAuth2": ["enrollment.read"]
          }
        ]
      },
      "post": {
        "tags": ["Enrollments"],
        "summary": "Create a new enrollment",
        "description": "Creates a new enrollment given the user and learning object id.",
        "operationId": "addEnrollment",
        "security": [
          {
            "OAuth2": ["enrollment.write"]
          }
        ]
      }
    },
    "/v2/enrollment-aggregates": {
      "get": {
        "tags": ["Enrollments"],
        "summary": "Get enrollment count of learning objects",
        "description": "Get learning objects which have enrollment numbers equal or larger than the provided parameter. Or get enrollment count for the learning object ids provided. At least one of the two parameter needs to be supplied. This endpoint is only available for users with administrator permissions.",
        "security": [
          {
            "OAuth2": ["enrollment.read"]
          }
        ]
      }
    },
    "/v2/enrollments/award": {
      "post": {
        "tags": ["Enrollments"],
        "summary": "Create a new award enrollment",
        "description": "Creates a new enrollment given the user and learning object id.",
        "security": [
          {
            "OAuth2": ["enrollment.write"]
          }
        ]
      }
    },
    "/v2/enrollments/{enrollment-id}": {
      "get": {
        "tags": ["Enrollments"],
        "summary": "Get enrollment details",
        "description": "Gets the enrollment for a given enrollment id. Note, only enrollment id is supported, the award and plan-assigned enrollment types are not supported.",
        "security": [
          {
            "OAuth2": ["enrollment.read"]
          }
        ]
      },
      "patch": {
        "tags": ["Enrollments"],
        "summary": "Update an enrollment",
        "description": "Update an enrollment for a given enrollment id.",
        "security": [
          {
            "OAuth2": ["enrollment.write"]
          }
        ]
      }
    },
    "/v2/enrollments/{enrollment-id}/goal": {
      "post": {
        "tags": ["Enrollments"],
        "summary": "Link an existing enrolment to a goal",
        "description": "Update an enrollment for a given enrollment id.",
        "security": [
          {
            "OAuth2": ["enrollment.write"]
          }
        ]
      }
    },
    "/v2/provider/enrollments": {
      "post": {
        "operationId": "EnrolmentsController_postProviderEnrolment",
        "summary": "Create or update an enrolment",
        "tags": ["Enrollments"],
        "security": [
          {
            "OAuth2": ["enrollment.write"]
          }
        ]
      }
    },
    "/v2/learning-objects": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "List learning objects",
        "description": "Search for learning objects.",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      },
      "post": {
        "operationId": "LearningObjectsController_postLearningObject",
        "summary": "Create a learning object",
        "tags": ["Learning Content"]
      }
    },
    "/v2/learning-objects/{lo-id}": {
      "get": {
        "operationId": "getLearningObjectDetails",
        "tags": ["Learning Content"],
        "summary": "Get learning object details",
        "description": "Detailed information about a learning object (LO).\nThe schema of the object returned depends on the LO type.\nCourses contain modules under `items`, and modules contain learning items under `items`.\nLearning items themselves have no `items`.\n",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/learning-objects/source/{source_id}": {
      "patch": {
        "operationId": "LearningObjectsController_patchLearningObject",
        "summary": "Patch a learning object by source_id",
        "tags": ["Learning Content"]
      },
      "get": {
        "operationId": "LearningObjectsController_getLearningObject",
        "tags": ["Learning Content"],
        "summary": "Get a learning object by source_id"
      }
    },
    "/v2/learning-objects/suggest/autocomplete": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Get autocomplete suggestion"
      }
    },
    "/v2/learning-objects/{lo-id}/custom-attributes": {
      "patch": {
        "tags": ["Learning Content"],
        "summary": "Update learning object custom attributes",
        "description": "If custom attributes for learning objects have been set up on the portal, this endpoint can be used to update the values of those custom attributes.\n",
        "security": [
          {
            "OAuth2": ["lo.write"]
          }
        ]
      }
    },
    "/v2/learning-objects/{lo-id}/preview": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Get preview URL for learning objects",
        "description": "Returns one or more URLs that can be embedded or directly used to preview a learning object.\n\nCan only be requested for learning objects whose `previewable` property equals `true`.\n",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/learning-objects/{lo-id}/similar": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Get similar learning objects (Experimental)",
        "description": "Returns one or more learning objects which are similar to the LO provided. The schema of the object returned depends on the LO type.\n",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/learning-objects/{lo-id}/scorm": {
      "get": {
        "tags": ["Learning Content"],
        "summary": "Download learning object as a SCORM package",
        "description": "Download learning object as a SCORM package.",
        "security": [
          {
            "OAuth2": ["lo.read"]
          }
        ]
      }
    },
    "/v2/onboard": {
      "post": {
        "tags": ["Onboarding"],
        "summary": "Creates new portals",
        "description": "Creates a new portal as well as a new user account if one doesn't exist. If it does exist, the existing users access token has to be used to make this request. This request can be made with tokens required using the grant type \"client_credentials\"",
        "security": [
          {
            "OAuth2": ["portal.write"]
          }
        ]
      }
    },
    "/v2/partners/content-group": {
      "post": {
        "tags": ["Partners"],
        "summary": "Add content group to child portals",
        "description": "Allow partners to add a content group to their child portal",
        "security": [
          {
            "OAuth2": ["portal.write"]
          }
        ]
      },
      "delete": {
        "tags": ["Partners"],
        "summary": "Remove content group from child portals",
        "description": "Allow partners to remove a content group from their child portal",
        "security": [
          {
            "OAuth2": ["portal.write"]
          }
        ]
      }
    },
    "/v2/me": {
      "get": {
        "tags": ["Users"],
        "summary": "Authenticated user details",
        "description": "Information about the authenticated user",
        "security": [
          {
            "OAuth2": ["user.read"]
          }
        ]
      },
      "patch": {
        "tags": ["Users"],
        "summary": "Update authenticated user details",
        "description": "Update information about the authenticated user",
        "security": [
          {
            "OAuth2": ["user.write"]
          }
        ]
      }
    },
    "/v2/me/login": {
      "post": {
        "tags": ["Users"],
        "summary": "Generate login link",
        "description": "Generate a single use login URL for the authenticated user.",
        "security": [
          {
            "OAuth2": ["user.login.me"]
          }
        ]
      }
    },
    "/v2/users": {
      "get": {
        "tags": ["Users"],
        "summary": "List users",
        "description": "Retrieves a list of users filtered by the given search criteria",
        "security": [
          {
            "OAuth2": ["user.read"]
          }
        ]
      },
      "post": {
        "tags": ["Users"],
        "summary": "Create new user",
        "description": "Will create a new user. An email will be sent to the user for them to login and set their password.",
        "security": [
          {
            "OAuth2": ["user.write"]
          }
        ]
      }
    },
    "/v2/users/{user-id}": {
      "get": {
        "tags": ["Users"],
        "summary": "Get user details",
        "description": "Get the user record",
        "security": [
          {
            "OAuth2": ["user.read"]
          }
        ]
      },
      "patch": {
        "tags": ["Users"],
        "summary": "Update user",
        "description": "Update user record",
        "security": [
          {
            "OAuth2": ["user.write"]
          }
        ]
      }
    },
    "/v2/users/{user-id}/login": {
      "post": {
        "tags": ["Users"],
        "summary": "Generate login link",
        "description": "Generate a single use login URL for a user. This is not enabled by default, please contact support@go1.com for access.",
        "security": [
          {
            "OAuth2": ["user.login"]
          }
        ]
      }
    },
    "/v2/users/reset_password": {
      "post": {
        "tags": ["Users"],
        "summary": "Reset a user's password",
        "description": "Given a valid email, this endpoint will send a password reset email to the email address.\nIf the OAuth token is a learner token, the given email has to be the learner's own email address, otherwise, it will return 403 error.\nIf the OAuth token is a portal admin token, the given email should belong to the admin user's portal, otherwise, it will return 200 as a silent error.\n",
        "security": [
          {
            "OAuth2": ["user.read"]
          }
        ]
      }
    },
    "/v2/groups": {
      "get": {
        "tags": ["User Groups"],
        "summary": "List of UserGroups in my portal",
        "description": "Retrieves a list of UserGroups limited to 50",
        "security": [
          {
            "OAuth2": ["group.read"]
          }
        ]
      },
      "post": {
        "tags": ["User Groups"],
        "summary": "Create a new UserGroup",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/groups/{group-id}": {
      "get": {
        "tags": ["User Groups"],
        "summary": "Get UserGroup detail",
        "description": "Gets the UserGroup detail for a given id.",
        "security": [
          {
            "OAuth2": ["group.read"]
          }
        ]
      },
      "put": {
        "tags": ["User Groups"],
        "summary": "Modify UserGroup detail",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      },
      "delete": {
        "tags": ["User Groups"],
        "summary": "Delete a UserGroup",
        "description": "Delete a UserGroup object for a given id.",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/groups/{group-id}/assignment": {
      "get": {
        "tags": ["User Groups"],
        "summary": "List of a certain UserGroup's assignments",
        "description": "Retrieves a list of assignments in a certain UserGroup limited to 50",
        "security": [
          {
            "OAuth2": ["group.read"]
          }
        ]
      }
    },
    "/v2/groups/{group-id}/membership": {
      "get": {
        "tags": ["User Groups"],
        "summary": "List of a certain UserGroup's memberships",
        "description": "Retrieves a list of memberships in a certain UserGroup limited to 50",
        "security": [
          {
            "OAuth2": ["group.read"]
          }
        ]
      }
    },
    "/v2/groups/membership": {
      "post": {
        "tags": ["User Groups"],
        "summary": "Create a UserGroup Membership",
        "description": "Creates the UserGroup Membership for a given UserGroup ID and User IDs.",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/groups/membership/{membership-id}": {
      "delete": {
        "tags": ["User Groups"],
        "summary": "Delete a UserGroup Membership",
        "description": "Delete a UserGroup object for a given UserGroup ID and an User ID.",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/groups/membership/delete": {
      "post": {
        "tags": ["User Groups"],
        "summary": "Delete multiple UserGroup Memberships by User IDs",
        "description": "Delete associate UserGroup Memberships with a given UserGroup ID and list of User IDs.",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/groups/assignment": {
      "post": {
        "tags": ["User Groups"],
        "summary": "Create a UserGroup Assignment",
        "description": "Creates the UserGroup Assignment for a given UserGroup ID and Learning Object IDs.",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/groups/assignment/delete": {
      "delete": {
        "tags": ["User Groups"],
        "summary": "Delete a UserGroup Assignment",
        "description": "Remove a assigned Learning Object from a UserGroup object for a given UserGroupId and a Learning Object ID.",
        "security": [
          {
            "OAuth2": ["group.write"]
          }
        ]
      }
    },
    "/v2/webhooks": {
      "get": {
        "tags": ["Webhooks"],
        "summary": "List webhooks",
        "description": "Retrieves a list of webhooks limited to 5 webhooks",
        "security": [
          {
            "OAuth2": ["webhook.read"]
          }
        ]
      },
      "post": {
        "tags": ["Webhooks"],
        "summary": "Create new webhook",
        "description": "Will create a new webhook. Note regarding \"content_decommission\" webhook. This will fire for all decomissioned items, even if your portal does not have access to it.",
        "security": [
          {
            "OAuth2": ["webhook.write"]
          }
        ]
      }
    },
    "/v2/webhooks/{webhook-id}": {
      "get": {
        "tags": ["Webhooks"],
        "summary": "Get webhook details",
        "description": "Get the webhook record",
        "security": [
          {
            "OAuth2": ["webhook.read"]
          }
        ]
      },
      "patch": {
        "tags": ["Webhooks"],
        "summary": "Update webhook",
        "description": "Update webhook object",
        "security": [
          {
            "OAuth2": ["webhook.write"]
          }
        ]
      },
      "delete": {
        "tags": ["Webhooks"],
        "summary": "Delete a webhook",
        "description": "Delete a webhook record",
        "security": [
          {
            "OAuth2": ["webhook.write"]
          }
        ]
      }
    },
    "/v2/graphql/query": {
      "post": {
        "tags": ["GraphQL"],
        "summary": "Fetch Learning Objects via a GraphQL endpoint",
        "description": "GO1 GraphQL Endpoints",
        "security": [
          {
            "OAuth2": [
              "enrollment.read",
              "enrollment.write",
              "lo.read",
              "lo.write",
              "portal.read",
              "portal.write",
              "user.read",
              "user.write"
            ]
          }
        ]
      }
    },
    "/v2/mapping/user-mapping/{portal-id}": {
      "get": {
        "tags": ["Data Mapping"],
        "summary": "Get Portal's User Mapping detail",
        "description": "Gets the User Mapping detail for a given portal id.",
        "security": [
          {
            "OAuth2": ["user.read"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://auth.go1.com/oauth/authorize",
            "tokenUrl": "https://auth.go1.com/oauth/token",
            "scopes": {
              "account.read": "Read account information",
              "enrollment.read": "Read enrollment data",
              "enrollment.write": "Manage enrollments",
              "lo.read": "Access content",
              "lo.write": "Manage content",
              "portal.read": "Read portal configuration",
              "portal.write": "Manage portal configuration",
              "user.login": "Create login link for the platform for other users",
              "user.login.me": "Create login link for the platform for the authenticated user",
              "user.read": "Read user data",
              "user.write": "Manage users",
              "group.read": "Read user group (membership, assignment) information",
              "group.write": "Manage user group (membership, assignment) information",
              "webhook.read": "Read webhook subscription configuration",
              "webhook.write": "Modify webhook subscription configuration"
            }
          }
        }
      }
    }
  }
}
